@@ -0,0 +1,14 @@
de  Vehiculo  importacion  *
clase  Carga ( Vehículo ):
    def  __init__ ( self , placa , conductor , capacidad , ejes ):
        vehiculo _ __init__ ( auto , placa , conductor )
        uno mismo __capacidad = capacidad
        uno mismo __ejes = ejes
    def  getPlaca ( auto ):
        devolverse  a uno mismo . __placa
    def  getCapacidad ( self ):
        devolverse  a uno mismo . __capacidad
    def  getConductor ( auto ):
        devolverse  a uno mismo . __conductor
    def  getEjes ( auto ):
        devolverse  a uno mismo . __ejes
