tupla1=(1,2,3,) #manera 1  de hacer dupla 
tupla2=9,8,7,6,5,4,3,2 #manera 2  de hacer dupla 
print(tupla1)
print(tupla2)


tupla1=(1,2,3,"sharon",) #se puede mexclar numeros y letras  
tupla1=(1,2,3,"sharon",[10,20]) #se puede mexclar tuplas y listas

print(tupla1)
print(tupla2)



tupla1=(1,2,3,) #manera   de hacer dupla 
print(len(tupla1))# len es el tamaño de la lista 

tupla2=9,8,7,6,5,4,3,2 #manera   de hacer dupla 
print(tupla2[1])# posicion teniendo encuenta que es 0 1 2 3 4 5 


tupla2=9,8,7,6,5,4,3,2 #manera   de hacer dupla 
print(tupla2[2:4])# posicion teniendo encuenta que es 0 1 2 3 4 5 etc

tupla1=tupla1*2 #manera   de hacer dupla 
print(tupla1)  


tupla1+=(100,) #manera   de hacer dupla 
print(tupla1) 




